# knowledge.py - PyDevBot Knowledge Base

SNIPPETS = {}
EXPLANATIONS = {}
BEST = {}

# ── SNIPPETS ──────────────────────────────────────────────────

SNIPPETS["inline_keyboard"] = (
    "Inline Keyboard with Callbacks",
    "```python\n"
    "from telegram import InlineKeyboardButton, InlineKeyboardMarkup\n"
    "\n"
    "async def show_menu(update, context):\n"
    "    keyboard = [\n"
    "        [InlineKeyboardButton('Yes', callback_data='yes'),\n"
    "         InlineKeyboardButton('No',  callback_data='no')],\n"
    "    ]\n"
    "    await update.message.reply_text(\n"
    "        'Choose:', reply_markup=InlineKeyboardMarkup(keyboard)\n"
    "    )\n"
    "\n"
    "async def button_handler(update, context):\n"
    "    query = update.callback_query\n"
    "    await query.answer()  # removes spinner\n"
    "    if query.data == 'yes':\n"
    "        await query.edit_message_text('You chose Yes!')\n"
    "    elif query.data == 'no':\n"
    "        await query.edit_message_text('You chose No!')\n"
    "\n"
    "# app.add_handler(CallbackQueryHandler(button_handler))\n"
    "```"
)

SNIPPETS["conversation_handler"] = (
    "ConversationHandler (multi-step form)",
    "```python\n"
    "from telegram.ext import ConversationHandler, CommandHandler, MessageHandler, filters\n"
    "\n"
    "NAME, AGE = range(2)\n"
    "\n"
    "async def start(update, context):\n"
    "    await update.message.reply_text('What is your name?')\n"
    "    return NAME\n"
    "\n"
    "async def get_name(update, context):\n"
    "    context.user_data['name'] = update.message.text\n"
    "    await update.message.reply_text('How old are you?')\n"
    "    return AGE\n"
    "\n"
    "async def get_age(update, context):\n"
    "    name = context.user_data['name']\n"
    "    age = update.message.text\n"
    "    await update.message.reply_text(f'Got it! {name}, {age} years old.')\n"
    "    return ConversationHandler.END\n"
    "\n"
    "async def cancel(update, context):\n"
    "    await update.message.reply_text('Cancelled.')\n"
    "    return ConversationHandler.END\n"
    "\n"
    "conv = ConversationHandler(\n"
    "    entry_points=[CommandHandler('start', start)],\n"
    "    states={\n"
    "        NAME: [MessageHandler(filters.TEXT & ~filters.COMMAND, get_name)],\n"
    "        AGE:  [MessageHandler(filters.TEXT & ~filters.COMMAND, get_age)],\n"
    "    },\n"
    "    fallbacks=[CommandHandler('cancel', cancel)],\n"
    ")\n"
    "```"
)

SNIPPETS["send_photo"] = (
    "Send Photo / File",
    "```python\n"
    "# From URL\n"
    "await context.bot.send_photo(\n"
    "    chat_id=update.effective_chat.id,\n"
    "    photo='https://example.com/image.png',\n"
    "    caption='Here is your image'\n"
    ")\n"
    "\n"
    "# Local file\n"
    "with open('image.png', 'rb') as f:\n"
    "    await context.bot.send_photo(chat_id=update.effective_chat.id, photo=f)\n"
    "\n"
    "# Document\n"
    "with open('report.pdf', 'rb') as f:\n"
    "    await context.bot.send_document(\n"
    "        chat_id=update.effective_chat.id,\n"
    "        document=f,\n"
    "        caption='Your report'\n"
    "    )\n"
    "```"
)

SNIPPETS["schedule_job"] = (
    "Schedule a Repeating Job",
    "```python\n"
    "from datetime import time\n"
    "import pytz\n"
    "\n"
    "async def daily_message(context):\n"
    "    await context.bot.send_message(\n"
    "        chat_id=context.job.chat_id,\n"
    "        text='Good morning! Daily reminder.'\n"
    "    )\n"
    "\n"
    "async def set_timer(update, context):\n"
    "    chat_id = update.effective_chat.id\n"
    "    # Cancel existing job\n"
    "    old = context.chat_data.get('job')\n"
    "    if old:\n"
    "        old.schedule_removal()\n"
    "    # Run every day at 9:00 AM UTC\n"
    "    job = context.job_queue.run_daily(\n"
    "        daily_message,\n"
    "        time=time(9, 0, tzinfo=pytz.utc),\n"
    "        chat_id=chat_id,\n"
    "    )\n"
    "    context.chat_data['job'] = job\n"
    "    await update.message.reply_text('Daily reminder set for 9 AM UTC!')\n"
    "```"
)

SNIPPETS["sqlite"] = (
    "SQLite Database with aiosqlite",
    "```python\n"
    "import aiosqlite\n"
    "\n"
    "DB = 'bot.db'\n"
    "\n"
    "async def init_db():\n"
    "    async with aiosqlite.connect(DB) as db:\n"
    "        await db.execute(\n"
    "            'CREATE TABLE IF NOT EXISTS users '\n"
    "            '(id INTEGER PRIMARY KEY, username TEXT, joined TEXT DEFAULT CURRENT_TIMESTAMP)'\n"
    "        )\n"
    "        await db.commit()\n"
    "\n"
    "async def save_user(user_id: int, username: str):\n"
    "    async with aiosqlite.connect(DB) as db:\n"
    "        await db.execute(\n"
    "            'INSERT OR IGNORE INTO users (id, username) VALUES (?, ?)',\n"
    "            (user_id, username)\n"
    "        )\n"
    "        await db.commit()\n"
    "\n"
    "async def get_user(user_id: int):\n"
    "    async with aiosqlite.connect(DB) as db:\n"
    "        async with db.execute('SELECT * FROM users WHERE id = ?', (user_id,)) as cur:\n"
    "            return await cur.fetchone()\n"
    "```"
)

SNIPPETS["fsm_aiogram"] = (
    "FSM in aiogram v3",
    "```python\n"
    "from aiogram import Router\n"
    "from aiogram.fsm.context import FSMContext\n"
    "from aiogram.fsm.state import State, StatesGroup\n"
    "from aiogram.filters import Command\n"
    "from aiogram.types import Message\n"
    "\n"
    "router = Router()\n"
    "\n"
    "class Form(StatesGroup):\n"
    "    name = State()\n"
    "    age  = State()\n"
    "\n"
    "@router.message(Command('start'))\n"
    "async def cmd_start(msg: Message, state: FSMContext):\n"
    "    await msg.answer('What is your name?')\n"
    "    await state.set_state(Form.name)\n"
    "\n"
    "@router.message(Form.name)\n"
    "async def process_name(msg: Message, state: FSMContext):\n"
    "    await state.update_data(name=msg.text)\n"
    "    await msg.answer('How old are you?')\n"
    "    await state.set_state(Form.age)\n"
    "\n"
    "@router.message(Form.age)\n"
    "async def process_age(msg: Message, state: FSMContext):\n"
    "    data = await state.get_data()\n"
    "    await msg.answer(f\"Hello {data['name']}, age {msg.text}!\")\n"
    "    await state.clear()\n"
    "```"
)

SNIPPETS["middleware_aiogram"] = (
    "Throttling Middleware in aiogram v3",
    "```python\n"
    "from aiogram import BaseMiddleware\n"
    "from aiogram.types import Message\n"
    "from typing import Callable, Any, Awaitable\n"
    "import time\n"
    "\n"
    "class ThrottlingMiddleware(BaseMiddleware):\n"
    "    def __init__(self, limit: float = 1.0):\n"
    "        self.limit = limit\n"
    "        self.users: dict[int, float] = {}\n"
    "\n"
    "    async def __call__(self, handler, event: Message, data):\n"
    "        uid = event.from_user.id\n"
    "        now = time.time()\n"
    "        if uid in self.users and now - self.users[uid] < self.limit:\n"
    "            await event.answer('Slow down! Too many messages.')\n"
    "            return\n"
    "        self.users[uid] = now\n"
    "        return await handler(event, data)\n"
    "\n"
    "# dp.message.middleware(ThrottlingMiddleware(limit=1.0))\n"
    "```"
)

SNIPPETS["env"] = (
    "Loading .env Variables",
    "```python\n"
    "# pip install python-dotenv\n"
    "from dotenv import load_dotenv\n"
    "import os\n"
    "\n"
    "load_dotenv()  # reads .env file\n"
    "\n"
    "TOKEN  = os.getenv('TELEGRAM_BOT_TOKEN')\n"
    "DB_URL = os.getenv('DATABASE_URL', 'sqlite:///bot.db')\n"
    "DEBUG  = os.getenv('DEBUG', 'false').lower() == 'true'\n"
    "\n"
    "# .env file example:\n"
    "# TELEGRAM_BOT_TOKEN=1234567890:AAFxxx...\n"
    "# DATABASE_URL=postgresql://user:pass@host/db\n"
    "# DEBUG=true\n"
    "```"
)

SNIPPETS["error_handler"] = (
    "Global Error Handler",
    "```python\n"
    "import traceback, logging\n"
    "logger = logging.getLogger(__name__)\n"
    "\n"
    "async def error_handler(update, context):\n"
    "    logger.error('Exception:', exc_info=context.error)\n"
    "    tb = ''.join(traceback.format_exception(\n"
    "        type(context.error), context.error, context.error.__traceback__\n"
    "    ))\n"
    "    if update and update.effective_message:\n"
    "        await update.effective_message.reply_text(\n"
    "            'Something went wrong. Please try again.'\n"
    "        )\n"
    "    # Notify admin\n"
    "    ADMIN_ID = 123456789\n"
    "    await context.bot.send_message(\n"
    "        chat_id=ADMIN_ID,\n"
    "        text=f'Error:\\n{tb[:3000]}'\n"
    "    )\n"
    "\n"
    "# app.add_error_handler(error_handler)\n"
    "```"
)

SNIPPETS["pagination"] = (
    "Paginated Results with Inline Buttons",
    "```python\n"
    "PER_PAGE = 5\n"
    "\n"
    "async def show_page(update, context, items, page=0):\n"
    "    start = page * PER_PAGE\n"
    "    chunk = items[start:start + PER_PAGE]\n"
    "    text  = '\\n'.join(f'{i+1+start}. {item}' for i, item in enumerate(chunk))\n"
    "    nav = []\n"
    "    if page > 0:\n"
    "        nav.append(InlineKeyboardButton('Prev', callback_data=f'page_{page-1}'))\n"
    "    if start + PER_PAGE < len(items):\n"
    "        nav.append(InlineKeyboardButton('Next', callback_data=f'page_{page+1}'))\n"
    "    kb = [nav] if nav else []\n"
    "    await update.message.reply_text(\n"
    "        text,\n"
    "        reply_markup=InlineKeyboardMarkup(kb) if kb else None\n"
    "    )\n"
    "```"
)

SNIPPETS["broadcast"] = (
    "Broadcast Message to All Users",
    "```python\n"
    "import asyncio\n"
    "\n"
    "async def broadcast(update, context):\n"
    "    if update.effective_user.id != ADMIN_ID:\n"
    "        return\n"
    "    text = ' '.join(context.args)\n"
    "    user_ids = await get_all_user_ids()  # your DB function\n"
    "    success, failed = 0, 0\n"
    "    for uid in user_ids:\n"
    "        try:\n"
    "            await context.bot.send_message(chat_id=uid, text=text)\n"
    "            success += 1\n"
    "        except Exception:\n"
    "            failed += 1\n"
    "        await asyncio.sleep(0.05)  # respect rate limits\n"
    "    await update.message.reply_text(\n"
    "        f'Done! Sent: {success} | Failed: {failed}'\n"
    "    )\n"
    "```"
)

SNIPPETS["decorator"] = (
    "Admin-only Decorator",
    "```python\n"
    "from functools import wraps\n"
    "\n"
    "ADMIN_IDS = {123456789}\n"
    "\n"
    "def admin_only(func):\n"
    "    @wraps(func)\n"
    "    async def wrapper(update, context):\n"
    "        if update.effective_user.id not in ADMIN_IDS:\n"
    "            await update.message.reply_text('Admins only.')\n"
    "            return\n"
    "        return await func(update, context)\n"
    "    return wrapper\n"
    "\n"
    "@admin_only\n"
    "async def admin_panel(update, context):\n"
    "    await update.message.reply_text('Welcome to admin panel!')\n"
    "```"
)

SNIPPETS["typing_action"] = (
    "Show Typing... Action",
    "```python\n"
    "from telegram import constants\n"
    "\n"
    "async def slow_command(update, context):\n"
    "    await update.message.chat.send_action(constants.ChatAction.TYPING)\n"
    "    result = await do_heavy_work()\n"
    "    await update.message.reply_text(result)\n"
    "\n"
    "# Other actions:\n"
    "# ChatAction.UPLOAD_PHOTO\n"
    "# ChatAction.UPLOAD_DOCUMENT\n"
    "# ChatAction.RECORD_VOICE\n"
    "```"
)

SNIPPETS["inline_query"] = (
    "Inline Query Handler",
    "```python\n"
    "from telegram import InlineQueryResultArticle, InputTextMessageContent\n"
    "import uuid\n"
    "\n"
    "async def inline_query(update, context):\n"
    "    query = update.inline_query.query.strip()\n"
    "    if not query:\n"
    "        return\n"
    "    results = [\n"
    "        InlineQueryResultArticle(\n"
    "            id=str(uuid.uuid4()),\n"
    "            title=f'Send: {query}',\n"
    "            input_message_content=InputTextMessageContent(query),\n"
    "        )\n"
    "    ]\n"
    "    await update.inline_query.answer(results)\n"
    "\n"
    "# app.add_handler(InlineQueryHandler(inline_query))\n"
    "# Enable in BotFather: /setinline\n"
    "```"
)

SNIPPETS["webhook"] = (
    "Webhook Setup with FastAPI",
    "```python\n"
    "from fastapi import FastAPI, Request\n"
    "from telegram import Update\n"
    "from telegram.ext import Application\n"
    "import os\n"
    "\n"
    "TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')\n"
    "WEBHOOK_URL = os.getenv('WEBHOOK_URL')  # e.g. https://app.railway.app\n"
    "\n"
    "app_tg = Application.builder().token(TOKEN).build()\n"
    "app    = FastAPI()\n"
    "\n"
    "@app.on_event('startup')\n"
    "async def startup():\n"
    "    await app_tg.initialize()\n"
    "    await app_tg.bot.set_webhook(f'{WEBHOOK_URL}/webhook')\n"
    "    await app_tg.start()\n"
    "\n"
    "@app.post('/webhook')\n"
    "async def webhook(req: Request):\n"
    "    data = await req.json()\n"
    "    update = Update.de_json(data, app_tg.bot)\n"
    "    await app_tg.process_update(update)\n"
    "    return {'ok': True}\n"
    "```"
)

# ── EXPLANATIONS ───────────────────────────────────────────────

EXPLANATIONS["conversationhandler"] = (
    "ConversationHandler lets your bot have multi-step conversations like a form wizard.\n\n"
    "How it works:\n"
    "- Define states (NAME = 0, AGE = 1)\n"
    "- Each state has handlers waiting for user input\n"
    "- Handlers return the next state (or ConversationHandler.END)\n"
    "- entry_points: what triggers the conversation (e.g. /start)\n"
    "- fallbacks: handles /cancel or unexpected input\n\n"
    "Key tip: Use filters.TEXT & ~filters.COMMAND inside states to block commands mid-conversation.\n\n"
    "Use /snippet conversation_handler to see a full example."
)

EXPLANATIONS["webhook"] = (
    "Polling vs Webhook\n\n"
    "POLLING: bot constantly asks Telegram 'any new messages?'\n"
    "- Simple setup, works anywhere\n"
    "- Slightly higher latency\n"
    "- Best for development and small bots\n\n"
    "WEBHOOK: Telegram pushes updates directly to your server\n"
    "- Needs a public HTTPS URL\n"
    "- Lower latency, more efficient\n"
    "- Best for production bots\n\n"
    "Rule: Dev = polling. Production with traffic = webhook.\n\n"
    "Use /snippet webhook to see FastAPI webhook setup."
)

EXPLANATIONS["fsm"] = (
    "FSM (Finite State Machine)\n\n"
    "FSM manages what state a user is currently in during a conversation.\n\n"
    "In python-telegram-bot: ConversationHandler handles FSM.\n"
    "In aiogram v3: built-in StatesGroup + FSMContext.\n\n"
    "Why use FSM?\n"
    "Without it, your bot has no memory between messages.\n"
    "With FSM, you know if a user is in step 1, step 2, or done.\n\n"
    "aiogram v3 FSM storage options:\n"
    "- MemoryStorage() - in-memory, lost on restart\n"
    "- RedisStorage() - persistent, survives restarts\n\n"
    "Use /snippet fsm_aiogram to see a full aiogram v3 example."
)

EXPLANATIONS["middleware"] = (
    "Middleware in aiogram v3\n\n"
    "Middleware intercepts every update before it hits your handler.\n\n"
    "Use cases:\n"
    "- Throttling / rate limiting\n"
    "- Logging all messages\n"
    "- Injecting database sessions\n"
    "- Checking if user is banned\n\n"
    "Order matters - middleware runs in the order you register it.\n\n"
    "Outer middleware (before and after handler):\n"
    "dp.update.outer_middleware(LoggingMiddleware())\n\n"
    "Inner middleware (only for matched handlers):\n"
    "dp.message.middleware(ThrottlingMiddleware())\n\n"
    "Use /snippet middleware_aiogram to see a throttling example."
)

EXPLANATIONS["jobqueue"] = (
    "Job Queue (Scheduling)\n\n"
    "PTB has a built-in scheduler to run tasks on a timer.\n\n"
    "Types:\n"
    "- run_once(callback, when) - run once after X seconds\n"
    "- run_repeating(callback, interval) - run every X seconds\n"
    "- run_daily(callback, time) - run every day at HH:MM\n"
    "- run_monthly(callback, day, time) - monthly\n\n"
    "JobQueue is auto-enabled in PTB v20+, no extra setup needed.\n\n"
    "Pass data to a job:\n"
    "job = context.job_queue.run_once(my_func, when=10, data={'key': 'val'}, chat_id=id)\n"
    "In callback: context.job.data['key']\n\n"
    "Use /snippet schedule_job for a daily reminder example."
)

EXPLANATIONS["inline_keyboard"] = (
    "Inline Keyboards Explained\n\n"
    "Inline keyboards are buttons that appear below a message.\n\n"
    "Button types:\n"
    "- callback_data - triggers CallbackQueryHandler\n"
    "- url - opens a URL\n"
    "- switch_inline_query - opens inline mode\n"
    "- web_app - opens a Telegram Web App\n\n"
    "Key rule: Always call await query.answer() first in callback handler.\n"
    "This removes the loading spinner from the button.\n\n"
    "Edit message after button press:\n"
    "await query.edit_message_text('New text!')\n\n"
    "Use /snippet inline_keyboard for a full example."
)

EXPLANATIONS["filters"] = (
    "Filters in PTB\n\n"
    "Filters decide which messages a handler responds to.\n\n"
    "Common filters:\n"
    "- filters.TEXT            - any text message\n"
    "- filters.COMMAND         - messages starting with /\n"
    "- filters.PHOTO           - photo messages\n"
    "- filters.Document.ALL    - any file\n"
    "- filters.Regex(r'^\\d+$') - matches regex\n"
    "- filters.User(user_ids=[123]) - specific users\n\n"
    "Combine with operators:\n"
    "- filters.TEXT & ~filters.COMMAND  - text but NOT a command\n"
    "- filters.PHOTO | filters.VIDEO    - photo OR video"
)

EXPLANATIONS["context_user_data"] = (
    "context.user_data / chat_data / bot_data\n\n"
    "PTB gives you free dictionaries to store temporary data.\n\n"
    "Per-user storage:\n"
    "context.user_data['score'] = 10\n\n"
    "Per-chat storage:\n"
    "context.chat_data['topic'] = 'python'\n\n"
    "Global bot storage:\n"
    "context.bot_data['total_users'] = 500\n\n"
    "WARNING: This data is in-memory only - lost when bot restarts!\n\n"
    "For persistence across restarts, use PicklePersistence:\n"
    "from telegram.ext import PicklePersistence\n"
    "p = PicklePersistence(filepath='bot_data.pkl')\n"
    "app = Application.builder().token(TOKEN).persistence(p).build()"
)

EXPLANATIONS["rate_limiting"] = (
    "Rate Limiting Your Bot\n\n"
    "Telegram limits: 30 messages/sec globally, 1 message/sec per chat.\n\n"
    "Simple per-user throttle:\n"
    "from collections import defaultdict\n"
    "import time\n\n"
    "last_msg = defaultdict(float)\n"
    "LIMIT = 1.0\n\n"
    "async def handle(update, context):\n"
    "    uid = update.effective_user.id\n"
    "    now = time.time()\n"
    "    if now - last_msg[uid] < LIMIT:\n"
    "        await update.message.reply_text('Please slow down!')\n"
    "        return\n"
    "    last_msg[uid] = now\n\n"
    "For aiogram use middleware - see /snippet middleware_aiogram"
)

# ── BEST ───────────────────────────────────────────────────────

BEST["database"] = (
    "Best Database for Telegram Bots\n\n"
    "Small bots (under 10k users):\n"
    "SQLite + aiosqlite - zero setup, file-based, fully async\n"
    "pip install aiosqlite\n\n"
    "Medium bots (10k-100k users):\n"
    "PostgreSQL + asyncpg or SQLAlchemy 2.0 (async)\n"
    "pip install asyncpg sqlalchemy[asyncio]\n\n"
    "Need caching or fast reads:\n"
    "Redis via redis.asyncio - great for sessions, rate limits\n\n"
    "Recommendation for beginners:\n"
    "Start with SQLite + aiosqlite. Use /snippet sqlite for example."
)

BEST["http"] = (
    "Best Async HTTP Client\n\n"
    "RECOMMENDED: httpx\n"
    "pip install httpx\n\n"
    "import httpx\n"
    "async with httpx.AsyncClient() as client:\n"
    "    r = await client.get('https://api.example.com/data')\n"
    "    data = r.json()\n\n"
    "Also good: aiohttp - more verbose but powerful\n\n
